CREATE SEQUENCE EVENT_SEQ;

CREATE TABLE EVENTS
(
    ID BIGINT NOT NULL PRIMARY KEY DEFAULT nextval('EVENT_SEQ'),
    CATEGORY INTEGER NOT NULL,
    SUB_CATEGORY INTEGER NOT NULL,
    TYPE INTEGER NOT NULL,
    CREATED TIMESTAMP NOT NULL,
    DESCRIPTION TEXT,
    READ BOOLEAN NOT NULL default false,
    DELETED BOOLEAN NOT NULL default false,
    ENTITY_TYPE INTEGER NOT NULL,
    ENTITY_ID BIGINT NOT NULL,
    SOURCE_ROLE_ID BIGINT NOT NULL constraint EVENT_SOURCE_ROLE_FKEY references ROLES,
    CHANGE_ROLE_ID BIGINT constraint EVENT_CHANGE_ROLE_FKEY references ROLES,
    EMPLOYEE_ID BIGINT NOT NULL constraint EVENT_EMPLOYEE_FKEY references EMPLOYEES
);