CREATE SEQUENCE COMPETENCE_SEQ;

CREATE TABLE COMPETENCES
(
    ID BIGINT NOT NULL PRIMARY KEY DEFAULT nextval('COMPETENCE_SEQ'),
    TITLE VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT
);

CREATE SEQUENCE ACTIVITY_SEQ;

CREATE TABLE ACTIVITIES
(
    ID BIGINT NOT NULL PRIMARY KEY DEFAULT nextval('ACTIVITY_SEQ'),
    TITLE VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
    WEIGHT INTEGER NOT NULL,
    INTERNAL_LINK VARCHAR(200) NOT NULL,
    COMPETENCE_ID BIGINT NOT NULL constraint ACTIVITY_COMPETENCE_FKEY references COMPETENCES
);

CREATE SEQUENCE AREA_SEQ;

CREATE TABLE AREAS
(
    ID BIGINT NOT NULL PRIMARY KEY DEFAULT nextval('AREA_SEQ'),
    TITLE VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT
);

CREATE SEQUENCE TRIBE_SEQ;

CREATE TABLE TRIBES
(
    ID BIGINT NOT NULL PRIMARY KEY DEFAULT nextval('TRIBE_SEQ'),
    TITLE VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT
);