CREATE SEQUENCE ROLE_SEQ;

CREATE TABLE ROLES
(
    ID BIGINT NOT NULL PRIMARY KEY DEFAULT nextval('ROLE_SEQ'),
    TITLE VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
    VALID_FROM TIMESTAMP NOT NULL,
    VALID_TO TIMESTAMP,
    EMPLOYEE_ID BIGINT NOT NULL
        constraint ROLE_EMPLOYEE_FKEY references EMPLOYEES
);

CREATE TABLE ROLE_ADMINS
(
    ID BIGINT NOT NULL PRIMARY KEY
        constraint ROLE_ADMIN_ROLE_FKEY references ROLES
);

CREATE TABLE ROLE_CHAPTER_LEADERS
(
    ID BIGINT NOT NULL PRIMARY KEY
            constraint ROLE_ADMIN_ROLE_FKEY references ROLES,
    CHAPTER_ID BIGINT NOT NULL
        constraint ROLE_CHAPTER_LEADER_CHAPTER_FKEY references CHAPTERS
);

CREATE TABLE ROLE_CHAPTER_MEMBERS
(
    ID BIGINT NOT NULL PRIMARY KEY
            constraint ROLE_ADMIN_ROLE_FKEY references ROLES,
    CHAPTER_ID BIGINT NOT NULL
        constraint ROLE_CHAPTER_MEMBER_CHAPTER_FKEY references CHAPTERS
);

CREATE TABLE ROLE_SQUAD_MEMBERS
(
    ID BIGINT NOT NULL PRIMARY KEY
            constraint ROLE_ADMIN_ROLE_FKEY references ROLES,
    SQUAD_ID BIGINT NOT NULL
        constraint ROLE_SQUAD_MEMBER_CHAPTER_FKEY references SQUADS
);