CREATE SEQUENCE SQUAD_SEQ;

CREATE TABLE SQUADS
(
    ID BIGINT NOT NULL PRIMARY KEY DEFAULT nextval('SQUAD_SEQ'),
    TITLE VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
    TRIBE_ID BIGINT NOT NULL
        constraint SQUAD_TRIBE_FKEY references TRIBES
);